[build]
builder = "NIXPACKS"
buildCommand = "npm ci"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "servicevision-backend"
port = 3001

[services.servicevision-backend]
internalPort = 3001
protocol = "tcp"